// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0gNoSj0ePqh_sw1xdPfzjO_DBw7nFGXI',
    appId: '1:387532925871:web:cea0bfee04a4b2211c1d5a',
    messagingSenderId: '387532925871',
    projectId: 'campus-guide-b82fe',
    authDomain: 'campus-guide-b82fe.firebaseapp.com',
    storageBucket: 'campus-guide-b82fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVokWFxh9Oo7qJdimX_maItcSh5WrqRdY',
    appId: '1:387532925871:android:495dc4f6887eacfa1c1d5a',
    messagingSenderId: '387532925871',
    projectId: 'campus-guide-b82fe',
    storageBucket: 'campus-guide-b82fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmnhA2JrryHOaicXadSr6b2yb_XQ8_SOM',
    appId: '1:387532925871:ios:5643798bd337db451c1d5a',
    messagingSenderId: '387532925871',
    projectId: 'campus-guide-b82fe',
    storageBucket: 'campus-guide-b82fe.firebasestorage.app',
    iosBundleId: 'com.example.campusGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmnhA2JrryHOaicXadSr6b2yb_XQ8_SOM',
    appId: '1:387532925871:ios:5643798bd337db451c1d5a',
    messagingSenderId: '387532925871',
    projectId: 'campus-guide-b82fe',
    storageBucket: 'campus-guide-b82fe.firebasestorage.app',
    iosBundleId: 'com.example.campusGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0gNoSj0ePqh_sw1xdPfzjO_DBw7nFGXI',
    appId: '1:387532925871:web:fc8f0a0b43fbfc4b1c1d5a',
    messagingSenderId: '387532925871',
    projectId: 'campus-guide-b82fe',
    authDomain: 'campus-guide-b82fe.firebaseapp.com',
    storageBucket: 'campus-guide-b82fe.firebasestorage.app',
  );

}